# Generated by Django 5.1 on 2024-10-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.SmallIntegerField(choices=[(1, 'ETANOL'), (2, 'FLEX'), (3, 'DIESEL'), (4, 'GASOLINA')]),
        ),
    ]
